# Generated by Django 4.2.1 on 2023-05-12 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TLDR_Backend_API_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='tos',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
