# Generated by Django 4.2.1 on 2023-05-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldr_app', '0002_alter_result_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tos', models.TextField()),
            ],
        ),
    ]
