# Generated by Django 4.2.1 on 2023-05-24 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tldr_app', '0003_tos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(default=dict)),
                ('tos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tldr_app.tos')),
            ],
        ),
    ]
