# Generated by Django 4.2.1 on 2023-05-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tldr_app', '0004_comparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='tos',
        ),
    ]
