# Generated by Django 4.2.1 on 2023-05-24 17:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tldr_app', '0005_remove_comparison_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tldr_app.user'),
        ),
        migrations.CreateModel(
            name='TosComparisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparisons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('tos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tldr_app.tos')),
            ],
        ),
    ]
